services:
  - type: web
    name: new-final-project-atec-backend
    env: python
    region: oregon
    branch: stage
    plan: free
    root: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT --proxy-headers --forwarded-allow-ips="*"
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./test.db
      - key: CLIENT_URL
        value: https://your-frontend-url
      - key: SECRET_KEY
        secure: true
      - key: STRIPE_PRIVATE_KEY
        secure: true
      - key: STRIPE_WEBHOOK_SECRET
        secure: true
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_HOST_USER
        secure: true
      - key: EMAIL_HOST_PASSWORD
        secure: true
      - key: EMAIL_FROM
        secure: true
      - key: BASE_URL
        value: "https://matricula.co.pt/API/reg.asmx/CheckPortugal"
      - key: USERNAME_API
        value: "yazyn"
      - key: GOOGLE_CLIENT_ID
        secure: true
      - key: GOOGLE_CLIENT_SECRET
        secure: true
      - key: FACEBOOK_CLIENT_ID
        secure: true
      - key: FACEBOOK_CLIENT_SECRET
        secure: true
